import './globals.css'
import { Inter } from 'next/font/google'
import { AuthProvider } from '@/context/AuthProvider'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Phamarcy System',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-blue-gray-50`}>
        <AuthProvider>
        {children}
        </AuthProvider>
      </body>
    </html>
  )
}
